services:

  db:
    image: shoon95/postgres
    build:
      context: ./db
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d moviedb -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
    expose:
      - "5432"
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moviedb

  web:
    image: shoon95/django
    build:
      context: ./crud
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: ["sh", "./start.sh"]
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: shoon95/nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web


    


    
