name: Github Actions

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - 'crud'
          - 'db'
          - 'nginx'  # Assuming the Dockerfile for the nginx directory is named 'Dockerfile'

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: teichae/node
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ky0328
          password: etoilekayla02
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.directory }}  # Use the specific directory
          file: ./${{ matrix.directory }}/Dockerfile  # Specify Dockerfile in the directory
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
