name: Github Actions

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - 'crud'
          - 'db'
          - 'nginx'

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ky0328
          password: etoilekayla02
      -
        name: Build and push
        run: |
          docker buildx create --use
          docker buildx build --file ./${{ matrix.directory }}/Dockerfile --platform linux/amd64 --tag teichae/node:${{ github.sha }} ./${{ matrix.directory }}
          docker push teichae/node:${{ github.sha }}
